#!/usr/bin/env node
/* ============================================================
   tools/build.js
   Generates per-slug HTML pages and sitemap.xml from the
   data files at the repo root.
   ------------------------------------------------------------
   Usage:
     node tools/build.js          (run from repo root)
   ------------------------------------------------------------
   How it works:
     1. Loads each data file in a tiny sandboxed "window" object
        so the assignments (window.RECIPES = [...]) populate
        a local data object.
     2. Walks each content type, writes a baked HTML page per
        non-draft slug, then writes sitemap.xml.
   ============================================================ */

const fs   = require("fs");
const path = require("path");
const vm   = require("vm");

const ROOT = path.resolve(__dirname, "..");

const DATA_FILES = [
  { file: "config.js",       key: "SITE" },
  { file: "recipes.js",      key: "RECIPES",      type: "recipe",       dir: "recipes" },
  { file: "techniques.js",   key: "TECHNIQUES",   type: "technique",    dir: "techniques" },
  { file: "insider.js",      key: "INSIDER",      type: "insider",      dir: "insider" },
  { file: "reviews.js",      key: "REVIEWS",      type: "review",       dir: "reviews" },
  { file: "troubleshoot.js", key: "TROUBLESHOOT", type: "troubleshoot", dir: "troubleshoot" },
  { file: "glossary.js",     key: "GLOSSARY",     type: "glossary",     dir: "glossary" },
  { file: "notebook.js",     key: "NOTEBOOK",     type: "notebook",     dir: "notebook" },
];

const sandbox = { window: {} };
vm.createContext(sandbox);

for (const f of DATA_FILES) {
  const fp = path.join(ROOT, f.file);
  if (!fs.existsSync(fp)) {
    console.warn(`! skip ${f.file} (not found)`);
    continue;
  }
  const src = fs.readFileSync(fp, "utf-8");
  vm.runInContext(src, sandbox, { filename: f.file });
}

const SITE = sandbox.window.SITE;
if (!SITE) { console.error("FATAL: config.js did not define window.SITE"); process.exit(1); }
const SITE_URL = SITE.url || "https://ecook.wiki";

function escapeHtml(s) {
  return String(s == null ? "" : s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#039;");
}

function absUrl(path) {
  if (!path) return "";
  if (/^https?:\/\//i.test(path)) return path;
  return SITE_URL + path;
}

function pageHtml(opts) {
  // opts: { type, slug, title, description, canonical, image }
  return `<!DOCTYPE html>
<!-- Generated by tools/build.js — do not edit by hand. -->
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(opts.title)}</title>
  <meta name="description" content="${escapeHtml(opts.description)}" />
  <link rel="canonical" href="${opts.canonical}" />
  <link rel="alternate" type="application/rss+xml" title="ecook.wiki — Shi'an's Notebook" href="/feed.xml" />

  <meta property="og:type"        content="article" />
  <meta property="og:site_name"   content="ecook.wiki" />
  <meta property="og:title"       content="${escapeHtml(opts.title)}" />
  <meta property="og:description" content="${escapeHtml(opts.description)}" />
  <meta property="og:url"         content="${opts.canonical}" />
  <meta property="og:image"       content="${opts.image}" />

  <meta name="twitter:card"        content="summary_large_image" />
  <meta name="twitter:title"       content="${escapeHtml(opts.title)}" />
  <meta name="twitter:description" content="${escapeHtml(opts.description)}" />
  <meta name="twitter:image"       content="${opts.image}" />

  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;1,400&family=Inter:wght@400;500;600&display=swap" />
  <link rel="stylesheet" href="/assets/style.css" />
</head>
<body>
  <main id="app"></main>

  <script>
    window.PAGE_TYPE = ${JSON.stringify(opts.type)};
    window.SLUG = ${JSON.stringify(opts.slug)};
  </script>
  <script src="/config.js"></script>
  <script src="/recipes.js"></script>
  <script src="/techniques.js"></script>
  <script src="/insider.js"></script>
  <script src="/reviews.js"></script>
  <script src="/troubleshoot.js"></script>
  <script src="/glossary.js"></script>
  <script src="/notebook.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/fuse.js@7.0.0/dist/fuse.min.js" defer></script>
  <script src="/assets/main.js" defer></script>
  <script src="/assets/search.js" defer></script>
</body>
</html>
`;
}

function ensureDir(p) { fs.mkdirSync(p, { recursive: true }); }

const sitemap = [
  { loc: SITE_URL + "/",              priority: "1.0", changefreq: "weekly" },
  { loc: SITE_URL + "/about/",        priority: "0.5", changefreq: "monthly" },
  { loc: SITE_URL + "/contact/",      priority: "0.3", changefreq: "yearly" },
  { loc: SITE_URL + "/privacy/",      priority: "0.3", changefreq: "yearly" },
  { loc: SITE_URL + "/terms/",        priority: "0.3", changefreq: "yearly" },
  { loc: SITE_URL + "/tools/pantry/", priority: "0.6", changefreq: "monthly" },
];

// Items collected for RSS feed
const feedItems = [];

let total = 0;
for (const f of DATA_FILES) {
  if (!f.dir) continue;                            // skip config
  const list = (sandbox.window[f.key] || []).filter(x => !x.draft);
  for (const item of list) {
    const slug = item.slug;
    if (!slug) { console.warn(`! ${f.file}: entry missing slug`); continue; }
    const canonical = `${SITE_URL}/${f.dir}/${slug}/`;
    const title = item.metaTitle || `${item.title} — ecook.wiki`;
    const description = item.metaDescription || item.subtitle || "";
    const image = item.cover ? absUrl(item.cover) : absUrl(SITE.defaultShareImage || "/images/share-default.jpg");
    const html = pageHtml({ type: f.type, slug, title, description, canonical, image });

    const out = path.join(ROOT, f.dir, slug, "index.html");
    ensureDir(path.dirname(out));
    fs.writeFileSync(out, html);
    total++;
    sitemap.push({
      loc: canonical,
      lastmod: item.lastModified || item.date,
      priority: f.type === "recipe" ? "0.8" : "0.7",
      changefreq: "monthly",
    });
    feedItems.push({
      title: item.title,
      link: canonical,
      description: item.metaDescription || item.subtitle || "",
      pubDate: item.date,
      image,
      type: f.type,
    });
  }
  console.log(`✓ ${f.dir}: ${list.length} pages`);
}

// sitemap.xml
const today = new Date().toISOString().slice(0, 10);
const smXml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${
  sitemap.map(u =>
    `  <url>\n    <loc>${u.loc}</loc>\n    <lastmod>${u.lastmod || today}</lastmod>\n    <changefreq>${u.changefreq || "monthly"}</changefreq>\n    <priority>${u.priority || "0.7"}</priority>\n  </url>`
  ).join("\n")
}\n</urlset>\n`;
fs.writeFileSync(path.join(ROOT, "sitemap.xml"), smXml);
console.log(`✓ sitemap.xml: ${sitemap.length} URLs`);

// feed.xml — RSS 2.0
function xmlEscape(s) {
  return String(s == null ? "" : s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&apos;");
}
function rfc822(isoDate) {
  // Accepts YYYY-MM-DD and returns RFC822 string required by RSS 2.0.
  const d = new Date(isoDate || Date.now());
  return d.toUTCString();
}
// Sort feedItems newest-first, cap at 40 entries (recommended)
feedItems.sort((a, b) => new Date(b.pubDate) - new Date(a.pubDate));
const recent = feedItems.slice(0, 40);
const feedXml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">
<channel>
  <title>${xmlEscape(SITE.name)}</title>
  <link>${SITE_URL}/</link>
  <atom:link href="${SITE_URL}/feed.xml" rel="self" type="application/rss+xml" />
  <description>${xmlEscape(SITE.description)}</description>
  <language>en</language>
  <copyright>© ${SITE.copyrightYear} ${xmlEscape(SITE.name)}</copyright>
  <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
${recent.map(it => `  <item>
    <title>${xmlEscape(it.title)}</title>
    <link>${it.link}</link>
    <guid isPermaLink="true">${it.link}</guid>
    <pubDate>${rfc822(it.pubDate)}</pubDate>
    <description>${xmlEscape(it.description)}</description>
    <enclosure url="${it.image}" type="image/png" length="0" />
  </item>`).join("\n")}
</channel>
</rss>
`;
fs.writeFileSync(path.join(ROOT, "feed.xml"), feedXml);
console.log(`✓ feed.xml: ${recent.length} items`);

console.log(`\nBuild complete — ${total} content pages generated.`);
